config/routes.rb
Rails.application.routes.draw do
  root "cars#index"
  resources :manufacturers, only: [:index, :show, :create, :new]
  resources :cars, only: [:index, :show, :create, :new]

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :manufacturer_id,
            :color,
            :year,
            :mileage,
            :name,
            presence: true
  validates :year,
            numericality: { greater_than: 1919 }

  belongs_to :manufacturer
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  validates :name,
            :country,
            presence: :true
  validates :name,
            uniqueness: { case_sensitive: false }

  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = "Successfully added a Car"
      redirect_to cars_path
    else
      render "new"
    end
  end

  def index
    @cars = Car.all
  end

  def show
    @car = Car.find_by(id: params["id"])
  end

  def car_params
    params.require(:car).permit(
      :manufacturer_id,
      :name,
      :year,
      :mileage,
      :color,
      :description
      )
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.create(manufacturer_params)
    if @manufacturer.save
      redirect_to manufacturers_path(@manufacturer)
    else
      render "new"
    end
  end

  def show
    @manufacturer = Manufacturer.find(params["id"])
  end

  def index
    @manufacturers = Manufacturer.all
  end

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/views/cars/index.html.erb
<ul>
  <% @cars.each do |car| %>
    <li><%= link_to car.name, car_path(car) %></li>
  <% end %>
</ul>

app/views/cars/new.html.erb
<% if @car.errors.any? %>
  <ul>
    <% @car.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @car do |f| %>
  <div>
    <%= f.label :manufacturer %>
    <%= f.collection_select(:manufacturer_id, Manufacturer.all, :id, :name) %>
  </div>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>
  <div>
    <%= f.label :mileage %>
    <%= f.number_field :mileage %>
  </div>
  <div>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/cars/show.html.erb
<h1><%= @car.name %></h1>
<ul>
  <li>Manufacturer: <%= @car.manufacturer.name %></li>
  <li>Year: <%= @car.year %></li>
  <li>Mileage: <%= @car.mileage %></li>
  <li>Color: <%= @car.color %></li>
</ul>
<p>Description: <%= @car.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Car Listings</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="left">
        <li class="active"><%= link_to 'New Car', new_car_path %></li>
        <li class="active"><%= link_to 'New Manufacturer', new_manufacturer_path %></li>
      </ul>
      <ul class="right">
          <li><%= link_to 'Cars', cars_path %></li>
          <li><%= link_to 'Manufacturers', manufacturers_path %></li>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li> <%= link_to manufacturer.name, manufacturer_path(manufacturer) %> </li>
  <% end %>
</ul>

app/views/manufacturers/new.html.erb
<% if @manufacturer.errors.any? %>
  <ul>
    <% @manufacturer.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @manufacturer do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/manufacturers/show.html.erb
<h1> Manufacturer </h1>
<ul>
  <li>Name: <%= @manufacturer.name %> </li>
  <li>Country: <%= @manufacturer.country %> </li>
</ul>